# docker build -t trixing/nightscout-stats -f Dockerfile.stats .
# docker tag trixing/nightscout-stats:latest registry.trixing.net/trixing/nightscout-stats:latest
# docker push registry.trixing.net/trixing/nightscout-stats:latest

FROM python:3

MAINTAINER Jan Dittmer <jdi@l4x.org>

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

CMD [ "python", "nightscout_stats_service.py" ]
